# this set up for development
version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: dev_db_kuliah_db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: kuliah_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/my.conf:/etc/mysql/my.conf
    networks:
      - kuliah_db_docker-networks

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: dev_phpmyadmin_kuliah_db
    restart: unless-stopped
    ports:
      - "1002:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    networks:
      - kuliah_db_docker-networks

networks:
  kuliah_db_docker-networks:
    driver: bridge

volumes:
  db:
    driver: local
